"""empty message

Revision ID: 047f494a3e78
Revises: ae88f1f3a19f
Create Date: 2023-09-11 12:01:56.480851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047f494a3e78'
down_revision = 'ae88f1f3a19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recommendations', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_saved_recommendation_uc', ['recommendation_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint('user_saved_recommendation_uc', type_='unique')

    # ### end Alembic commands ###
