"""empty message

Revision ID: 077cf53d6b50
Revises: 93abe4656906
Create Date: 2023-09-13 14:01:34.868616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077cf53d6b50'
down_revision = '93abe4656906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('updated', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('updated')
        batch_op.drop_column('published')

    # ### end Alembic commands ###
