"""empty message

Revision ID: 225e36fbb29a
Revises: 10ac7d8828ea
Create Date: 2023-09-11 09:11:23.295167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225e36fbb29a'
down_revision = '10ac7d8828ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_recommendation_uc', ['user_id', 'recommendation_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_constraint('user_recommendation_uc', type_='unique')

    # ### end Alembic commands ###
