"""empty message

Revision ID: c65d5f23bb2e
Revises: e8ca2c0c7a44
Create Date: 2023-09-10 13:54:24.892053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65d5f23bb2e'
down_revision = 'e8ca2c0c7a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_constraint('recommendation_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('recommendation_fiction_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'fiction_type', ['fiction_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recommendation_fiction_type_id_fkey', 'fiction_type', ['fiction_type_id'], ['id'])
        batch_op.create_foreign_key('recommendation_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
